Revert "recovery: change the way of rebooting when using power key combo"
code doesn't compile:

  bootable/recovery/ui.cpp: In member function 'void RecoveryUI::ProcessKey(int, int)':
  bootable/recovery/ui.cpp:177:60: error: 'property_set' was not declared in this scope
                   property_set(ANDROID_RB_PROPERTY, "reboot,");
                                                            ^
  make: ***   [out/target/product/generic/obj/EXECUTABLES/recovery_intermediates/ui.o] Error 1

This reverts commit 074c1c2312746aba29e1ffdf133685c8213c7378.

Change-Id: I3e0a24279e202df29308ce41eaacc86bfde89e5a